### ISSUE TITLE
49_DBMS_ASS2

### ISSUE THREAD

**Issue by UNKN0WN006** [Arnob-B/Study#2]
In question no. 10, its said display the id name and salary and salary grade who earns the amx salary for their department. But you have given 3. WHile there hare 4 people viz, King with 5000, Scott with 3000, FOrd with 3000 and Blake with 2850. So if possible go through it again.

**Comment by Arnob-B** [comment]
Firstly Thank you for pointing the mistake .
I have resolved the issue in my latest commit.
