### ISSUE TITLE
Question 5 for finding the factorial of a number

### ISSUE THREAD

**Issue by UNKN0WN006** [Arnob-B/Study#5]
In Assignment folder, for Assignment 4, when I am running the output for any value's result that is anyone's factorial, I am always getting 00 in paths 0040 to 0042. Pkease check what's the matter with the code.

**Comment by UNKN0WN006** [comment]
![WhatsApp Image 2024-11-28 at 17 01 40_0786a2ef](https://github.com/user-attachments/assets/894a52b0-572f-497b-8845-de848457a81c)

**Comment by Arnob-B** [comment]
16 bit no present in 0030 and 0031 is put in CX register. 
so if you only give value to 0030 then the default value in 0031 will make the factorial too large to compute.
as a result you get 00 00 00 from ds:0040 onwards
